/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordToPdfRouteImport } from './routes/word-to-pdf'
import { Route as VideoToAudioRouteImport } from './routes/video-to-audio'
import { Route as TiktokVideoDownloaderRouteImport } from './routes/tiktok-video-downloader'
import { Route as TiktokProfileDownloaderRouteImport } from './routes/tiktok-profile-downloader'
import { Route as PdfToWordRouteImport } from './routes/pdf-to-word'
import { Route as CompressWordRouteImport } from './routes/compress-word'
import { Route as CompressPdfRouteImport } from './routes/compress-pdf'
import { Route as AudioConverterRouteImport } from './routes/audio-converter'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsWordToPdfRouteImport } from './routes/tools.word-to-pdf'
import { Route as ToolsVideoToAudioRouteImport } from './routes/tools.video-to-audio'
import { Route as ToolsTiktokVideoDownloaderRouteImport } from './routes/tools.tiktok-video-downloader'
import { Route as ToolsTiktokProfileDownloaderRouteImport } from './routes/tools.tiktok-profile-downloader'
import { Route as ToolsPdfToWordRouteImport } from './routes/tools.pdf-to-word'
import { Route as ToolsCompressWordRouteImport } from './routes/tools.compress-word'
import { Route as ToolsCompressPdfRouteImport } from './routes/tools.compress-pdf'
import { Route as ToolsAudioConverterRouteImport } from './routes/tools.audio-converter'

const WordToPdfRoute = WordToPdfRouteImport.update({
  id: '/word-to-pdf',
  path: '/word-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoToAudioRoute = VideoToAudioRouteImport.update({
  id: '/video-to-audio',
  path: '/video-to-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokVideoDownloaderRoute = TiktokVideoDownloaderRouteImport.update({
  id: '/tiktok-video-downloader',
  path: '/tiktok-video-downloader',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokProfileDownloaderRoute = TiktokProfileDownloaderRouteImport.update({
  id: '/tiktok-profile-downloader',
  path: '/tiktok-profile-downloader',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToWordRoute = PdfToWordRouteImport.update({
  id: '/pdf-to-word',
  path: '/pdf-to-word',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressWordRoute = CompressWordRouteImport.update({
  id: '/compress-word',
  path: '/compress-word',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressPdfRoute = CompressPdfRouteImport.update({
  id: '/compress-pdf',
  path: '/compress-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioConverterRoute = AudioConverterRouteImport.update({
  id: '/audio-converter',
  path: '/audio-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWordToPdfRoute = ToolsWordToPdfRouteImport.update({
  id: '/tools/word-to-pdf',
  path: '/tools/word-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsVideoToAudioRoute = ToolsVideoToAudioRouteImport.update({
  id: '/tools/video-to-audio',
  path: '/tools/video-to-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTiktokVideoDownloaderRoute =
  ToolsTiktokVideoDownloaderRouteImport.update({
    id: '/tools/tiktok-video-downloader',
    path: '/tools/tiktok-video-downloader',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsTiktokProfileDownloaderRoute =
  ToolsTiktokProfileDownloaderRouteImport.update({
    id: '/tools/tiktok-profile-downloader',
    path: '/tools/tiktok-profile-downloader',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsPdfToWordRoute = ToolsPdfToWordRouteImport.update({
  id: '/tools/pdf-to-word',
  path: '/tools/pdf-to-word',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCompressWordRoute = ToolsCompressWordRouteImport.update({
  id: '/tools/compress-word',
  path: '/tools/compress-word',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCompressPdfRoute = ToolsCompressPdfRouteImport.update({
  id: '/tools/compress-pdf',
  path: '/tools/compress-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAudioConverterRoute = ToolsAudioConverterRouteImport.update({
  id: '/tools/audio-converter',
  path: '/tools/audio-converter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio-converter': typeof AudioConverterRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/compress-word': typeof CompressWordRoute
  '/pdf-to-word': typeof PdfToWordRoute
  '/tiktok-profile-downloader': typeof TiktokProfileDownloaderRoute
  '/tiktok-video-downloader': typeof TiktokVideoDownloaderRoute
  '/video-to-audio': typeof VideoToAudioRoute
  '/word-to-pdf': typeof WordToPdfRoute
  '/tools/audio-converter': typeof ToolsAudioConverterRoute
  '/tools/compress-pdf': typeof ToolsCompressPdfRoute
  '/tools/compress-word': typeof ToolsCompressWordRoute
  '/tools/pdf-to-word': typeof ToolsPdfToWordRoute
  '/tools/tiktok-profile-downloader': typeof ToolsTiktokProfileDownloaderRoute
  '/tools/tiktok-video-downloader': typeof ToolsTiktokVideoDownloaderRoute
  '/tools/video-to-audio': typeof ToolsVideoToAudioRoute
  '/tools/word-to-pdf': typeof ToolsWordToPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio-converter': typeof AudioConverterRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/compress-word': typeof CompressWordRoute
  '/pdf-to-word': typeof PdfToWordRoute
  '/tiktok-profile-downloader': typeof TiktokProfileDownloaderRoute
  '/tiktok-video-downloader': typeof TiktokVideoDownloaderRoute
  '/video-to-audio': typeof VideoToAudioRoute
  '/word-to-pdf': typeof WordToPdfRoute
  '/tools/audio-converter': typeof ToolsAudioConverterRoute
  '/tools/compress-pdf': typeof ToolsCompressPdfRoute
  '/tools/compress-word': typeof ToolsCompressWordRoute
  '/tools/pdf-to-word': typeof ToolsPdfToWordRoute
  '/tools/tiktok-profile-downloader': typeof ToolsTiktokProfileDownloaderRoute
  '/tools/tiktok-video-downloader': typeof ToolsTiktokVideoDownloaderRoute
  '/tools/video-to-audio': typeof ToolsVideoToAudioRoute
  '/tools/word-to-pdf': typeof ToolsWordToPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio-converter': typeof AudioConverterRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/compress-word': typeof CompressWordRoute
  '/pdf-to-word': typeof PdfToWordRoute
  '/tiktok-profile-downloader': typeof TiktokProfileDownloaderRoute
  '/tiktok-video-downloader': typeof TiktokVideoDownloaderRoute
  '/video-to-audio': typeof VideoToAudioRoute
  '/word-to-pdf': typeof WordToPdfRoute
  '/tools/audio-converter': typeof ToolsAudioConverterRoute
  '/tools/compress-pdf': typeof ToolsCompressPdfRoute
  '/tools/compress-word': typeof ToolsCompressWordRoute
  '/tools/pdf-to-word': typeof ToolsPdfToWordRoute
  '/tools/tiktok-profile-downloader': typeof ToolsTiktokProfileDownloaderRoute
  '/tools/tiktok-video-downloader': typeof ToolsTiktokVideoDownloaderRoute
  '/tools/video-to-audio': typeof ToolsVideoToAudioRoute
  '/tools/word-to-pdf': typeof ToolsWordToPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audio-converter'
    | '/compress-pdf'
    | '/compress-word'
    | '/pdf-to-word'
    | '/tiktok-profile-downloader'
    | '/tiktok-video-downloader'
    | '/video-to-audio'
    | '/word-to-pdf'
    | '/tools/audio-converter'
    | '/tools/compress-pdf'
    | '/tools/compress-word'
    | '/tools/pdf-to-word'
    | '/tools/tiktok-profile-downloader'
    | '/tools/tiktok-video-downloader'
    | '/tools/video-to-audio'
    | '/tools/word-to-pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audio-converter'
    | '/compress-pdf'
    | '/compress-word'
    | '/pdf-to-word'
    | '/tiktok-profile-downloader'
    | '/tiktok-video-downloader'
    | '/video-to-audio'
    | '/word-to-pdf'
    | '/tools/audio-converter'
    | '/tools/compress-pdf'
    | '/tools/compress-word'
    | '/tools/pdf-to-word'
    | '/tools/tiktok-profile-downloader'
    | '/tools/tiktok-video-downloader'
    | '/tools/video-to-audio'
    | '/tools/word-to-pdf'
  id:
    | '__root__'
    | '/'
    | '/audio-converter'
    | '/compress-pdf'
    | '/compress-word'
    | '/pdf-to-word'
    | '/tiktok-profile-downloader'
    | '/tiktok-video-downloader'
    | '/video-to-audio'
    | '/word-to-pdf'
    | '/tools/audio-converter'
    | '/tools/compress-pdf'
    | '/tools/compress-word'
    | '/tools/pdf-to-word'
    | '/tools/tiktok-profile-downloader'
    | '/tools/tiktok-video-downloader'
    | '/tools/video-to-audio'
    | '/tools/word-to-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioConverterRoute: typeof AudioConverterRoute
  CompressPdfRoute: typeof CompressPdfRoute
  CompressWordRoute: typeof CompressWordRoute
  PdfToWordRoute: typeof PdfToWordRoute
  TiktokProfileDownloaderRoute: typeof TiktokProfileDownloaderRoute
  TiktokVideoDownloaderRoute: typeof TiktokVideoDownloaderRoute
  VideoToAudioRoute: typeof VideoToAudioRoute
  WordToPdfRoute: typeof WordToPdfRoute
  ToolsAudioConverterRoute: typeof ToolsAudioConverterRoute
  ToolsCompressPdfRoute: typeof ToolsCompressPdfRoute
  ToolsCompressWordRoute: typeof ToolsCompressWordRoute
  ToolsPdfToWordRoute: typeof ToolsPdfToWordRoute
  ToolsTiktokProfileDownloaderRoute: typeof ToolsTiktokProfileDownloaderRoute
  ToolsTiktokVideoDownloaderRoute: typeof ToolsTiktokVideoDownloaderRoute
  ToolsVideoToAudioRoute: typeof ToolsVideoToAudioRoute
  ToolsWordToPdfRoute: typeof ToolsWordToPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/word-to-pdf': {
      id: '/word-to-pdf'
      path: '/word-to-pdf'
      fullPath: '/word-to-pdf'
      preLoaderRoute: typeof WordToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-to-audio': {
      id: '/video-to-audio'
      path: '/video-to-audio'
      fullPath: '/video-to-audio'
      preLoaderRoute: typeof VideoToAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok-video-downloader': {
      id: '/tiktok-video-downloader'
      path: '/tiktok-video-downloader'
      fullPath: '/tiktok-video-downloader'
      preLoaderRoute: typeof TiktokVideoDownloaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok-profile-downloader': {
      id: '/tiktok-profile-downloader'
      path: '/tiktok-profile-downloader'
      fullPath: '/tiktok-profile-downloader'
      preLoaderRoute: typeof TiktokProfileDownloaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-word': {
      id: '/pdf-to-word'
      path: '/pdf-to-word'
      fullPath: '/pdf-to-word'
      preLoaderRoute: typeof PdfToWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress-word': {
      id: '/compress-word'
      path: '/compress-word'
      fullPath: '/compress-word'
      preLoaderRoute: typeof CompressWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress-pdf': {
      id: '/compress-pdf'
      path: '/compress-pdf'
      fullPath: '/compress-pdf'
      preLoaderRoute: typeof CompressPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-converter': {
      id: '/audio-converter'
      path: '/audio-converter'
      fullPath: '/audio-converter'
      preLoaderRoute: typeof AudioConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/word-to-pdf': {
      id: '/tools/word-to-pdf'
      path: '/tools/word-to-pdf'
      fullPath: '/tools/word-to-pdf'
      preLoaderRoute: typeof ToolsWordToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/video-to-audio': {
      id: '/tools/video-to-audio'
      path: '/tools/video-to-audio'
      fullPath: '/tools/video-to-audio'
      preLoaderRoute: typeof ToolsVideoToAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/tiktok-video-downloader': {
      id: '/tools/tiktok-video-downloader'
      path: '/tools/tiktok-video-downloader'
      fullPath: '/tools/tiktok-video-downloader'
      preLoaderRoute: typeof ToolsTiktokVideoDownloaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/tiktok-profile-downloader': {
      id: '/tools/tiktok-profile-downloader'
      path: '/tools/tiktok-profile-downloader'
      fullPath: '/tools/tiktok-profile-downloader'
      preLoaderRoute: typeof ToolsTiktokProfileDownloaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-to-word': {
      id: '/tools/pdf-to-word'
      path: '/tools/pdf-to-word'
      fullPath: '/tools/pdf-to-word'
      preLoaderRoute: typeof ToolsPdfToWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/compress-word': {
      id: '/tools/compress-word'
      path: '/tools/compress-word'
      fullPath: '/tools/compress-word'
      preLoaderRoute: typeof ToolsCompressWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/compress-pdf': {
      id: '/tools/compress-pdf'
      path: '/tools/compress-pdf'
      fullPath: '/tools/compress-pdf'
      preLoaderRoute: typeof ToolsCompressPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/audio-converter': {
      id: '/tools/audio-converter'
      path: '/tools/audio-converter'
      fullPath: '/tools/audio-converter'
      preLoaderRoute: typeof ToolsAudioConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioConverterRoute: AudioConverterRoute,
  CompressPdfRoute: CompressPdfRoute,
  CompressWordRoute: CompressWordRoute,
  PdfToWordRoute: PdfToWordRoute,
  TiktokProfileDownloaderRoute: TiktokProfileDownloaderRoute,
  TiktokVideoDownloaderRoute: TiktokVideoDownloaderRoute,
  VideoToAudioRoute: VideoToAudioRoute,
  WordToPdfRoute: WordToPdfRoute,
  ToolsAudioConverterRoute: ToolsAudioConverterRoute,
  ToolsCompressPdfRoute: ToolsCompressPdfRoute,
  ToolsCompressWordRoute: ToolsCompressWordRoute,
  ToolsPdfToWordRoute: ToolsPdfToWordRoute,
  ToolsTiktokProfileDownloaderRoute: ToolsTiktokProfileDownloaderRoute,
  ToolsTiktokVideoDownloaderRoute: ToolsTiktokVideoDownloaderRoute,
  ToolsVideoToAudioRoute: ToolsVideoToAudioRoute,
  ToolsWordToPdfRoute: ToolsWordToPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
